# Generated by Django 5.0 on 2023-12-15 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drive_axle_model',
            fields=[
                ('Name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Engine_model',
            fields=[
                ('Name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Model_of_equipment',
            fields=[
                ('Name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Node_otkaz',
            fields=[
                ('Name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service_company',
            fields=[
                ('Name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Steering_axle_model',
            fields=[
                ('Name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission_model',
            fields=[
                ('Name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Type_TO',
            fields=[
                ('Name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Way',
            fields=[
                ('Name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('Number', models.IntegerField(blank=True, null=True)),
                ('Zav_number_machine', models.IntegerField(primary_key=True, serialize=False)),
                ('Zav_number_engine', models.CharField(blank=True, max_length=200, null=True)),
                ('Zav_number_transmission', models.CharField(blank=True, max_length=200, null=True)),
                ('Zav_number_drive_axle', models.CharField(blank=True, max_length=200, null=True)),
                ('Zav_number_steering_axle', models.CharField(blank=True, max_length=200, null=True)),
                ('Date_shipment', models.DateField(blank=True, null=True)),
                ('Buyer', models.CharField(blank=True, max_length=1000, null=True)),
                ('Consignee', models.CharField(blank=True, max_length=1000, null=True)),
                ('Delivery_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Configuration', models.CharField(blank=True, max_length=1000, null=True)),
                ('Drive_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hakaton.drive_axle_model')),
                ('Engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hakaton.engine_model')),
                ('Model_of_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hakaton.model_of_equipment')),
                ('Service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hakaton.service_company')),
                ('Steering_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hakaton.steering_axle_model')),
                ('Transmission_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hakaton.transmission_model')),
            ],
        ),
        migrations.CreateModel(
            name='TO_output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_TO', models.DateField(blank=True, null=True)),
                ('Operating_time', models.IntegerField(blank=True, null=True)),
                ('Number_work_order', models.CharField(blank=True, max_length=200, null=True)),
                ('Date_work_order', models.DateField(blank=True, null=True)),
                ('Service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hakaton.service_company')),
                ('Zav_number_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hakaton.machine')),
                ('Type_TO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hakaton.type_to')),
            ],
        ),
        migrations.CreateModel(
            name='Reklamacia_output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_otkaz', models.DateField(blank=True, null=True)),
                ('Operating_time', models.IntegerField(blank=True, null=True)),
                ('Description_otkaz', models.CharField(blank=True, max_length=200, null=True)),
                ('Used', models.CharField(blank=True, max_length=200, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Time', models.IntegerField(blank=True, null=True)),
                ('Node_otkaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hakaton.node_otkaz')),
                ('Zav_number_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hakaton.machine')),
                ('Way', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hakaton.way')),
            ],
        ),
    ]
